name: Main
on: [push]
jobs:
  build_test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: senolatac/sha-java-action@v4
        with:
          codacy-project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
